const KEY="mis_or_db_v1";const INITIAL="./data_inicial.json";let rows=[],filter="all";const $=id=>document.getElementById(id);
function normDate(v){if(!v)return"";if(typeof v==="string"){let m=v.match(/^(\d{4})[-/](\d{1,2})[-/](\d{1,2})$/);if(m)return`${m[1]}-${String(m[2]).padStart(2,"0")}-${String(m[3]).padStart(2,"0")}`;let d=new Date(v);if(!isNaN(d))return d.toISOString().slice(0,10)}if(typeof v==="number"){let d=new Date(Math.round((v-25569)*86400*1000));return d.toISOString().slice(0,10)}return""}
function daysSince(s){let d=new Date(normDate(s)+"T00:00:00");if(isNaN(d))return-1;return Math.floor((Date.now()-d.getTime())/86400000)}
function keyOf(r){return String(r["Número orden"]??r.numero??"").trim()}function getDate(r){return normDate(r["Fecha orden"]||r["fecha_creado"]||r.fecha)}function desc(r){return r["Descripción línea"]||r.descripcion||""}function prov(r){return r["Nombre proveedor"]||r.proveedor||""}
async function load(){let saved=localStorage.getItem(KEY);if(saved){try{rows=JSON.parse(saved)}catch(e){rows=[]}}if(!rows.length){try{rows=await(await fetch(INITIAL)).json();save()}catch(e){}}render();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});requestNotifications()}
function save(){localStorage.setItem(KEY,JSON.stringify(rows))}function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){let q=$("search").value.toLowerCase().trim(),groups=new Map();rows.forEach(r=>{let k=keyOf(r)||"(sin número)";if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)});let all=[...groups.entries()].map(([num,rs])=>({num,rs,r:rs[0],days:daysSince(getDate(rs[0]))}));$("total").textContent=groups.size;$("alerts").textContent=all.filter(x=>x.days>=30).length;$("recent").textContent=all.filter(x=>x.days>=21&&x.days<30).length;
let arr=all.filter(x=>!q||JSON.stringify(x.rs).toLowerCase().includes(q)).filter(x=>filter==="all"||(filter==="alert"&&x.days>=30)||(filter==="recent"&&x.days>=21&&x.days<30));
$("list").innerHTML=arr.map(x=>{let cls=x.days>=30?"alert":x.days>=21?"warn":"",status=x.days>=30?"🔴 +30 días":x.days>=21?"🟡 "+x.days+" días":"🟢 "+(x.days<0?"sin fecha":x.days+" días"),r=x.r;return`<article class="or ${cls}"><h3>OR ${esc(x.num)} <span class="pill">${status}</span></h3><div class="meta"><b>Descripción:</b> ${esc(desc(r)||"—")}<br><b>Proveedor:</b> ${esc(prov(r)||"—")}<br><b>Fecha creación:</b> ${esc(getDate(r)||"—")}<br><b>Entrega prometida:</b> ${esc(normDate(r["F entrega prometida"])||"—")}<br><b>Líneas:</b> ${x.rs.length}</div></article>`}).join("")||`<div class="panel">No se encontraron OR.</div>`}
$("search").oninput=render;document.querySelectorAll(".filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
function openNew(){$("modal").classList.remove("hidden");$("f_num").value="";$("f_desc").value="";$("f_prov").value="";$("f_date").value=new Date().toISOString().slice(0,10);$("f_due").value="";$("f_state").value="Pendiente";$("f_obs").value=""}function closeModal(){$("modal").classList.add("hidden")}$("newBtn").onclick=openNew;$("closeModal").onclick=closeModal;
$("orForm").onsubmit=e=>{e.preventDefault();let r={"Número orden":$("f_num").value.trim(),"Descripción línea":$("f_desc").value.trim(),"Nombre proveedor":$("f_prov").value.trim(),"Fecha orden":$("f_date").value,"F entrega prometida":$("f_due").value,"Último estado":$("f_state").value.trim(),"Observaciones app":$("f_obs").value.trim()};if(!r["Número orden"])return;rows.push(r);save();closeModal();render();notify("Nueva OR agregada",`OR ${r["Número orden"]} fue agregada correctamente.`)};
function merge(a,b){let m=new Map();[...a,...b].forEach(r=>{let k=keyOf(r)+"|"+JSON.stringify(r["Número línea"]??"");if(k!=="|")m.set(k,r)});return[...m.values()]}
$("excelInput").onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(typeof XLSX==="undefined")throw Error("lector Excel no disponible");let wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true}),incoming=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:""});rows=merge(rows,incoming);save();render();alert("Excel incorporado sin borrar las OR existentes.")}catch(err){alert("No se pudo importar el Excel: "+err.message)}e.target.value=""};
$("backupBtn").onclick=()=>{let blob=new Blob([JSON.stringify(rows,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="respaldo_mis_OR.json";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$("restoreInput").onchange=e=>{let f=e.target.files[0];if(!f)return;let rd=new FileReader();rd.onload=()=>{try{rows=merge(rows,JSON.parse(rd.result));save();render();alert("Respaldo restaurado sin eliminar OR existentes.")}catch(err){alert("Respaldo no válido.")}};rd.readAsText(f)};
async function requestNotifications(){if("Notification"in window&&Notification.permission==="default"){try{await Notification.requestPermission()}catch(e){}}checkAlerts()}function notify(t,b){if("Notification"in window&&Notification.permission==="granted"){try{new Notification(t,{body:b})}catch(e){}}}
function checkAlerts(){let seen=JSON.parse(localStorage.getItem("mis_or_alertas")||"{}"),today=new Date().toISOString().slice(0,10),groups=new Map();rows.forEach(r=>groups.set(keyOf(r),r));groups.forEach((r,num)=>{let d=daysSince(getDate(r));if(num&&d>=30&&seen[num]!==today){notify("Alerta de OR",`La OR ${num} tiene ${d} días desde su creación.`);seen[num]=today}});localStorage.setItem("mis_or_alertas",JSON.stringify(seen))}
load();